schema:
  - schema/*.graphql

exec:
  filename: graphql/generated/generated.go
  package: generated

model:
  filename: model/graphql_generated.go
  package: model

resolver:
  layout: follow-schema
  dir: graphql
  package: graphql

autobind:
  - github.com/ShinsakuYagi/gql-upload-sample/model

models:
  String:
    model:
      - github.com/99designs/gqlgen/graphql.String
